### PR TITLE
Binary queue implementation

### PR DESCRIPTION
**Pull request by ringods**
This PR contains an implementation of a binary queue. The data structure uses an Erlang `:queue` internally to contain the `binary` data.

At push, the given `binary` data is added as a single element on the underlying Erlang `:queue`. At pull time, we will assemble a single binary taking just enough from the underlying queue.

This is a first implementation. I will optimize the implementation later if it would be possible to reduce the amount of binary copying.

### CODE REVIEW

**Comment by comboy** [comment]
Thanks a lot!

So this is FILO, basically a binary heap, right? Out of curiosity, do you have need for this kind of heap in some project or was it mostly done for fun?

If I'm understanding correctly the main advantage of this over operating on binary is performance.

So I tried writing some benchmark, but I'm getting unexpected results. Either my understanding of this queue is wrong or there is some bug e.g.:

    [push: <<5, 208, 224, 23, 85>>, pull: 4, push: <<82, 203>>, push: <<98, 184, 169, 196>>]
    utime split: 414, utime queue: 409
    results match: false
    <<98, 184, 169, 196, 82, 203, 85>> # split_at result
    <<85, 82, 203, 98, 184, 169, 196>> # queue result

Here's the benchmark script I'm using: https://gist.github.com/comboy/92bcbbf10fbc3da3fbec09b816767f3a

I haven't yet carefully reviewed the code, wanting to make sure that my understanding is correct first.

**Comment by ringods** [comment]
No, this is FIFO, as in a queue. 

My need is for an application I'm building where I stream uploaded binaries to a GenStage. This queue is the state for the GenStage producer. In my Phoenix app, I disable Plug.Upload and replace it with code of my own which pushes the binary data to the producer. The consumer pulls data from the producer. As a result, I have a real streaming binary upload rather than using the intermediate Plug.Upload temporary file.

I haven't looked at your gist yet, but if you tested it as FILO, you indeed get weird results. 😄 

Given the instructions I see in your quoted example:

```
push: <<5, 208, 224, 23, 85>>
-> queue = <<5, 208, 224, 23, 85>>

pull: 4
-> result = <<5, 208, 224, 23>>
-> queue = <<85>>

push:  <<82, 203>>
-> queue = <<85, 82, 203>>

push: <<98, 184, 169, 196>>
-> queue = <<85, 82, 203, 98, 184, 169, 196>>
```

Only the internal storage is not as is shown here.

**Comment by comboy** [comment]
Oh, that's clever, nice. So yes as FIFO (`data <> queue` => `queue <> data` in the gist), as expected for some tiny binaries there's some penalty, but when pushing bigger data there's a noticeable improvement (hard to give some exact number since there are a few variables involved, but I've seen down to almost 1/3 of the original time, usually it seems to be ~30% improvement). 

I like it. So the idea from comments is that if pushed data would be > chunk_size, we would split it first, and that's it, right? 

As much as I like contributions to the lib I'm not sure if it doesn't deserve it's own lib to keep this one as a simple `:binary` wrapper. But I have no strong opinion one way or another. Let me know what you think.

Btw, do you plan to release this streaming upload thing? Probably lots of work to wrap it as a lib, but it does sound pretty cool.

**Comment by ringods** [comment]
@comboy I consider my queue submission small enough, and still just datatype related, to be included in this lib. If you look at the NodeJS community, they seem to create libs for a single javascript file. I don't want to go that way in this case. 😃 

The streaming upload thing is still future work, but the design and some ad-hoc code is finished. Now to make it truly work and scale in a real application. Once in that state, I can think of how to publish it.

Can we get this merged in and released first so I can add a clean Mix package dependency to this lib?

**Comment by comboy** [comment]
Sure, I'm happy to. I was a bit busy today, I'll do that tomorrow and I'll bump the lib version and push it hex.

I'd skip the comment at the end of the file and leave it as some low priority issue and it would be nice to have \@docs for all public functions to be consistent with the rest of the lib even if those won't be super insightful. But those are details, I can do it while merging.

**Comment by ringods** [comment]
Hang on. I will add more detailed docs first. BTW, are you happy with the API? I first tried to mimic the Erlang `:queue` api with `in` and `out`, but `in` seems to be a reserved word in Elixir, so that didn't work.

**Comment by comboy** [comment]
Yeah I'm not sure why `import Kernel, except: [{:in, 2}]` doesn't work, but current API seems fine to me.

**Comment by ringods** [comment]
@comboy documentation added! 😃

**Comment by comboy** [comment]
Wow, beautiful.

Plus I've learned about `@opaque`

I'll try to bump version and push the package today. Thanks a lot, you've clearly put a lot of effort to make it as nicely done as it is.

**Comment by ringods** [comment]
Well, I'm working my way into all matters Elixir. Definitely learning a lot myself along the way. 😉

**Pull request merged**
